In [8]:
import pandas as pd

In [10]:
cleaned_df = pd.read_csv("C:\\Users\\temisola\\Final-Year-Project\\datasets\\full_dataset_checkpoint.csv")

print(cleaned_df.shape)
cleaned_df.head()

(2272, 45)

,entry_id,part_id,part_code,part_theme,letter,yoruba,english_literal,interpretation_gold,quality_flag,has_yoruba_diacritics,...,mistral_prompt_tokens,mistral_completion_tokens,mistral_total_tokens,llama_translation,llama_interpretation,llama_raw,llama_error,llama_prompt_tokens,llama_completion_tokens,llama_total_tokens
0,016beb1f83885794,1,1A,"humility, self-control, self-knowledge, self-r...",A,Àgbéré àwòdì ní ńní òun ó jẹ ìgbín.,It is an overreaching kite that proposes to ea...,Know your limits.,OK,True,...,142.0,44.0,186.0,The snail shell is what the snail eats.,One's circumstances or resources can be the so...,"{\n ""translation"": ""The snail shell is what t...",NaN,147.0,42.0,189.0
1,041e7cc871bfebac,1,1a,"humility, self-control, self-knowledge, self-r...",A,A kì í kórira ọ̀fọ́n-ọ̀n ká finá bọ ahéré.,One does not so hate the bush rat that one set...,One should not destroy oneself simply to get a...,OK,True,...,154.0,46.0,200.0,We do not use a single rope to tie a bundle of...,Unity and cooperation are necessary to achieve...,"{\n ""translation"": ""We do not use a single ro...",NaN,150.0,39.0,189.0
2,04d43584d1d8404a,1,1a,"humility, self-control, self-knowledge, self-r...",A,A kì í bọ òrìṣà lójú ọ̀fọ́n-ọ̀n; bó bá dalé...,One does not sacrifice to a god in the presenc...,Do not do things that might constitute temptat...,OK,True,...,167.0,59.0,226.0,We do not worship the god of the forest in the...,One should respect the norms and conventions o...,"{\n ""translation"": ""We do not worship the god...",NaN,166.0,52.0,218.0
3,0524e60d4f486d54,1,1a,"humility, self-control, self-knowledge, self-r...",A,"Àrí-ì-gbọdọ̀-wí, baálé ilé yọkun lémú.","Something-seen-but-unmentionable, the man of t...","When a venerable person acts like a fool, few ...",OK,True,...,147.0,52.0,199.0,"The one who does not listen to advice, the own...",Disregarding advice can lead to loss and chaos.,"{\n ""translation"": ""The one who does not list...",NaN,152.0,47.0,199.0
4,0584b5795ae7ccb8,1,1a,"humility, self-control, self-knowledge, self-r...",A,Àwòrò tí a ò bá lù kì í luni.,A priest one does not hit does not hit one.,A person who wants to be respected must respec...,OK,False,...,136.0,38.0,174.0,The dawn that we did not greet will not greet us.,One must acknowledge and respect the beginning...,"{\n ""translation"": ""The dawn that we did not ...",NaN,142.0,46.0,188.0

In [12]:
translation_cols = [c for c in cleaned_df.columns if "_translation" in c]
interpretation_cols = [c for c in cleaned_df.columns if "_interpretation" in c]

In [13]:
required_cols = translation_cols + interpretation_cols

cleaned_df = cleaned_df[
    cleaned_df[required_cols]
    .apply(lambda x: x.astype(str).str.strip() != "")
    .all(axis=1)
]

In [16]:
base_columns = [
    "entry_id",
    "yoruba",
    "english_literal",
    "interpretation_gold"
]

In [17]:
keep_columns = base_columns + translation_cols + interpretation_cols

cleaned_df = cleaned_df[keep_columns]

In [18]:
print(cleaned_df.shape)
cleaned_df.head()

(2272, 14)

,entry_id,yoruba,english_literal,interpretation_gold,deepseek_translation,claude_translation,gemini_translation,mistral_translation,llama_translation,deepseek_interpretation,claude_interpretation,gemini_interpretation,mistral_interpretation,llama_interpretation
0,016beb1f83885794,Àgbéré àwòdì ní ńní òun ó jẹ ìgbín.,It is an overreaching kite that proposes to ea...,Know your limits.,The kite's talon says it will eat the snail.,The kite that carries snails says it will eat ...,The hawk's foolishness is that it thinks it wi...,The kite boasts that it will eat the snail.,The snail shell is what the snail eats.,This proverb warns against making empty boasts...,Someone who has access to or control over some...,It is foolish to attempt something impossible ...,It warns against overconfidence in one's abili...,One's circumstances or resources can be the so...
1,041e7cc871bfebac,A kì í kórira ọ̀fọ́n-ọ̀n ká finá bọ ahéré.,One does not so hate the bush rat that one set...,One should not destroy oneself simply to get a...,We do not hate the grinding stone and use fire...,One does not hate a wasp so much as to use fir...,One does not hate the buffalo so much as to se...,We do not gather dry twigs to set a hut on fire,We do not use a single rope to tie a bundle of...,Do not destroy something useful while expressi...,The cure should not be worse than the problem ...,One should not cause greater harm to oneself o...,One should not deliberately create or escalate...,Unity and cooperation are necessary to achieve...
2,04d43584d1d8404a,A kì í bọ òrìṣà lójú ọ̀fọ́n-ọ̀n; bó bá dalé...,One does not sacrifice to a god in the presenc...,Do not do things that might constitute temptat...,We do not worship the deity in the presence of...,One does not worship a deity in the presence o...,One does not worship an Orisha in the open; wh...,We do not worship the deity in the presence of...,We do not worship the god of the forest in the...,This proverb advises discretion and the import...,Sacred or important activities should not be p...,It is unwise to perform sacred rituals or reve...,"Laziness hinders progress, but persistence and...",One should respect the norms and conventions o...
3,0524e60d4f486d54,"Àrí-ì-gbọdọ̀-wí, baálé ilé yọkun lémú.","Something-seen-but-unmentionable, the man of t...","When a venerable person acts like a fool, few ...","The one who says 'I must not speak', the landl...","The one who must not be spoken against, the he...","The one who sees but must not speak, the head ...","The one who must not be scolded, the head of t...","The one who does not listen to advice, the own...",Silence in the face of wrongdoing can lead to ...,A respected authority figure has the power to ...,This proverb describes a situation where one i...,A person who is above reproach often has hidde...,Disregarding advice can lead to loss and chaos.
4,0584b5795ae7ccb8,Àwòrò tí a ò bá lù kì í luni.,A priest one does not hit does not hit one.,A person who wants to be respected must respec...,The hoe that is not used does not have an owner.,The plate that is not beaten does not make sound.,A priest that we do not beat does not beat us.,A drummer that one does not pay does not play ...,The dawn that we did not greet will not greet us.,Unused resources or tools are neglected and lo...,"If you don't take action or make an effort, yo...",One should not provoke or antagonize others if...,People expect compensation or appreciation for...,One must acknowledge and respect the beginning...

In [24]:
before_rows = len(cleaned_df)

ai_required_cols = [
    "deepseek_translation", "deepseek_interpretation",
    "claude_translation", "claude_interpretation",
    "gemini_translation", "gemini_interpretation",
    "llama_translation", "llama_interpretation",
    "mistral_translation", "mistral_interpretation"
]

mask_complete = (
    cleaned_df[ai_required_cols].notna().all(axis=1) &
    cleaned_df[ai_required_cols].apply(
        lambda col: col.astype(str).str.strip() != ""
    ).all(axis=1)
)

cleaned_df = cleaned_df[mask_complete].copy()

after_rows = len(cleaned_df)

print(f"Rows before cleaning: {before_rows}")
print(f"Rows after cleaning:  {after_rows}")
print(f"Rows removed:         {before_rows - after_rows}")

Rows before cleaning: 954
Rows after cleaning:  954
Rows removed:         0

In [25]:
cleaned_df.to_csv( "C:\\Users\\temisola\\Final-Year-Project\\datasets\\yoruba_proverb_final_cleaned.csv", index=False, encoding="utf-8-sig")